CREATE TABLE IF NOT EXISTS T_USER(id INT(11) PRIMARY KEY AUTO_INCREMENT, username VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, security_ques INT(11) NOT NULL, security_ans VARCHAR(255) NOT NULL);
INSERT INTO T_USER(username, email, password, security_ques, security_ans) VALUES('sysadmin1', 'mahbubur.rahman@informatik.hs-fulda.de', '123456', 1, 'hello world');
INSERT INTO T_USER(username, email, password, security_ques, security_ans) VALUES('sysadmin2', 'mahbubur.rahman@informatik.hs-fulda.de', '123457', 1, 'hello world');
INSERT INTO T_USER(username, email, password, security_ques, security_ans) VALUES('sysadmin3', 'mahbubur.rahman@informatik.hs-fulda.de', '123458', 1, 'hello world');

----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS T_TYPE(id INT(11) PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255) NOT NULL, parent_type INT(11));
INSERT INTO T_TYPE(name, parent_type) VALUES('SECURITY_QUES', null);
INSERT INTO T_TYPE(name, parent_type) VALUES('COUNTRY', null);
INSERT INTO T_TYPE(name, parent_type) VALUES('STATE', 2);
INSERT INTO T_TYPE(name, parent_type) VALUES('CITY', 3);
INSERT INTO T_TYPE(name, parent_type) VALUES('DESIGNATION', null);
INSERT INTO T_TYPE(name, parent_type) VALUES('TITLE', null);
INSERT INTO T_TYPE(name, parent_type) VALUES('GENDER', null);

------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS T_TYPE_VALUE(id INT(11) PRIMARY KEY AUTO_INCREMENT, type_id INT(11), value VARCHAR(255) NOT NULL, parent_type_value INT(11));
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(1, 'What is your city name', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(1, 'What is your school name', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(1, 'Tell us your favorite color name', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(2, 'Germany', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(2, 'Bangladesh', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(2, 'India', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(2, 'Iran', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(3, 'Hesse', 4);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(3, 'Baden-Württemberg', 4);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(3, 'Bavaria', 4);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(3, 'Berlin', 4);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(3, 'Brandenburg', 4);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(4, 'Fulda', 8);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(4, 'Frankfurt-am-Main', 8);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(4, 'Berlin', 11);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(5, 'Listing Agent', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(5, 'Buying Agent', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(5, 'Dual Agent', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(5, 'Builder', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(5, 'Inspector', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(5, 'Photographer', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(6, 'Mr.', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(6, 'Mrs.', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(6, 'Prof.', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(6, 'Dr.', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(6, 'Master', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(6, 'Miss', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(7, 'Male', null);
INSERT INTO T_TYPE_VALUE(type_id, value, parent_type_value) VALUES(7, 'Female', null);

----------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS T_URL(id INT(11) PRIMARY KEY AUTO_INCREMENT, url VARCHAR(255) NOT NULL);
INSERT INTO T_URL(url) VALUES('/biig/rest/properties');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties?filter=field:operator:value&sort=field:direction');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/status');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/state');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/sales');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/sales/{sale_id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/sales/');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/sales/{sale_id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/sales/{sale_id}/status');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/sales/{sale_id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/rents');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/rents/{rent_id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/rents/');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/rents/{rent_id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/rents/{rent_id}/status');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/rents/{rent_id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/leases');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/leases/{lease_id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/leases/');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/leases/{lease_id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/leases/{lease_id}/status');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/leases/{lease_id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/mortgages');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/mortgages/{mortgage_id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/mortgages/');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/mortgages/{mortgage_id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/mortgages/{mortgage_id}/status');
INSERT INTO T_URL(url) VALUES('/biig/rest/properties/{id}/mortgages/{mortgage_id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/users/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/users/{id}/dashboard');
INSERT INTO T_URL(url) VALUES('/biig/rest/users/{id}/messages');
INSERT INTO T_URL(url) VALUES('/biig/rest/users/{id}/messages/{msg_id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/users/{id}/logs');
INSERT INTO T_URL(url) VALUES('/biig/rest/users/');
INSERT INTO T_URL(url) VALUES('/biig/rest/users/login');
INSERT INTO T_URL(url) VALUES('/biig/rest/users/{id}/messages/send');
INSERT INTO T_URL(url) VALUES('/biig/rest/users/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/users/{id}/logout');
INSERT INTO T_URL(url) VALUES('/biig/rest/users/{id}/reset-password');
INSERT INTO T_URL(url) VALUES('/biig/rest/users/{id}/change-username');
INSERT INTO T_URL(url) VALUES('/biig/rest/users/{id}/subscribe');
INSERT INTO T_URL(url) VALUES('/biig/rest/users/{id}/unsubscribe');
INSERT INTO T_URL(url) VALUES('/biig/rest/users/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/customers');
INSERT INTO T_URL(url) VALUES('/biig/rest/customers/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/customers/');
INSERT INTO T_URL(url) VALUES('/biig/rest/customers/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/customers/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/companies');
INSERT INTO T_URL(url) VALUES('/biig/rest/companies/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/companies/');
INSERT INTO T_URL(url) VALUES('/biig/rest/companies/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/companies/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/employees');
INSERT INTO T_URL(url) VALUES('/biig/rest/employees?filter=field:operator:value&sort=field:direction');
INSERT INTO T_URL(url) VALUES('/biig/rest/employees/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/employees/');
INSERT INTO T_URL(url) VALUES('/biig/rest/employees/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/employees/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/roles');
INSERT INTO T_URL(url) VALUES('/biig/rest/roles/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/roles/');
INSERT INTO T_URL(url) VALUES('/biig/rest/roles/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/roles/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/urls');
INSERT INTO T_URL(url) VALUES('/biig/rest/urls/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/urls/');
INSERT INTO T_URL(url) VALUES('/biig/rest/urls/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/urls/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/types');
INSERT INTO T_URL(url) VALUES('/biig/rest/types/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/types/');
INSERT INTO T_URL(url) VALUES('/biig/rest/types/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/types/{id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/types/{id}/values');
INSERT INTO T_URL(url) VALUES('/biig/rest/types/{id}/values/{value_id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/types/{id}/values/');
INSERT INTO T_URL(url) VALUES('/biig/rest/types/{id}/values/{value_id}');
INSERT INTO T_URL(url) VALUES('/biig/rest/types/{id}/values/{value_id}');

---------------------------------------------------------------------------------------------
