alter table typevalue auto_increment = 1;
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(1, 'What is the name of your hometown?', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(1, 'What is the name of your first school?', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(1, 'What is your favourite colour?', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(11, 'Listing Agent', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(11, 'Company Admin', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(21, 'Mr.', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(21, 'Mrs.', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(21, 'Prof.', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(21, 'Dr.', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(21, 'Master', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(21, 'Miss', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(31, 'House', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(31, 'Apartment', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(31, 'Room', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(41, 'Residential', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(41, 'Commercial', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(51, 'Unfurnished', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(51, 'Semi Furnished', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(51, 'Fully Furnished', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(61, 'Price: High to Low', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(61, 'Price: Low to High', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(61, 'Age: New to Old', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(61, 'Age: Old to New', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(61, 'Newest First', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(71, '< 50', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(71, '51 - 100', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(71, '101 - 200', null);
INSERT INTO typevalue(parenttype, value, parenttypevalue) VALUES(71, '> 200', null);
